### ISSUE TITLE
Explosion controller doesn't work

### ISSUE THREAD

**Issue by GormAuslander** [Patbox/get-off-my-lawn-reserved#62]
Minecraft version is 1.20.1
Fabric version 0.16.10
Mod version 1.9.4+

I place the Explosion Controller anchor augment next to the anchor in the same manner as others (and I confirmed the flight anchor was working), and it shows in the anchor augment menu, and I can toggle it on and off, but it does not stop creepers from destroying blocks

**Comment by HeresJohnny320** [comment]
@GormAuslander are you using lithium ? something I just found out today is if you have lithium on your server then tnt and creepers will blow up in ur claim but if you go into ur lithium.properties and add this line mixin.world.explosions:false then save and restart ur server should fix that issue you can play around with more settings listed here https://github.com/CaffeineMC/lithium/blob/develop/lithium-fabric-mixin-config.md

**Comment by GormAuslander** [comment]
I am not using lithium currently

**Comment by GormAuslander** [comment]
> [@GormAuslander](https://github.com/GormAuslander) are you using lithium ? something I just found out today is if you have lithium on your server then tnt and creepers will blow up in ur claim but if you go into ur lithium.properties and add this line mixin.world.explosions:false then save and restart ur server should fix that issue you can play around with more settings listed here https://github.com/CaffeineMC/lithium/blob/develop/lithium-fabric-mixin-config.md

I'm not using lithium, but the fact that this is an issue makes me wonder if another one of my mods is changing mixin world explosions.

**Comment by ZekeZDev** [comment]
have no other mods except goml, this still happens on latest 1.21.4.

**Comment by Patbox** [comment]
Explosion controller toggles *unknown* explosions (so from things like dispensers, redstone, etc). Natural/directly player caused ones aren't protected, through maybe that should be an option

**Comment by ZekeZDev** [comment]
100% should be an option. Players are using it to grief, even just a global option would be good.

**Comment by GormAuslander** [comment]
Yes, I think a config toggle would be great

**Comment by GormAuslander** [comment]
> have no other mods except goml, this still happens on latest 1.21.4.

You just said two weeks ago that you tried this

**Comment by ZekeZDev** [comment]
> > have no other mods except goml, this still happens on latest 1.21.4.
> 
> You just said two weeks ago that you tried this

thought I had lithium disabled, I have it as a default dep in most of my packs.
